# Generated by Django 6.1 on 2026-08-29 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_post_description_post_short_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='category',
            new_name='category_id',
        ),
    ]
