# Generated by Django 6.1 on 2026-08-29 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_rename_category_video_category_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='category_id',
            new_name='category',
        ),
    ]
