# Generated by Django 6.1 on 2026-08-29 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_rename_category_id_video_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='thumbnail_public_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='thumbnail_url',
            field=models.URLField(null=True),
        ),
    ]
